""" lfmain_ui.py --

 UI generated by GUI Builder Build 146 on 2010-04-12 18:18:22 from:
    /media/data/hubi/code/python/little-frinc/src/lfmain.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Lfmain(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._frame_2 = Tkinter.Frame(self._frame_1,
        )
        self._frame_3 = Tkinter.Frame(self._frame_1,
        )
        self._frame_4 = Tkinter.Frame(self._frame_3,
        )
        self._frame_6 = Tkinter.Frame(self._frame_3,
        )
        self._frame_5 = Tkinter.Frame(self._frame_4,
        )
        self._labelframe_1 = Tkinter.LabelFrame(self._frame_6,
            text = "status & log",
        )
        self._frame_7 = Tkinter.Frame(self._frame_6,
        )
        self._frame_8 = Tkinter.Frame(self._frame_7,
        )
        self._frame_10 = Tkinter.Frame(self._labelframe_1,
        )
        self._frame_9 = Tkinter.Frame(self._frame_8,
        )
        self._butExit = Tkinter.Button(self._frame_2,
            text = "exit",
            width = 10,
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_2,
            height = 0,
            width = 0,
        )
        self._lsPackets = Tkinter.Listbox(self._frame_4,
            activestyle = "dotbox",
            borderwidth = 1,
            height = 0,
            width = 0,
        )
        self._sclPackets = Tkinter.Scrollbar(self._frame_4,
        )
        self._butKillpacket = Tkinter.Button(self._frame_5,
            text = "kill",
            width = 10,
        )
        self._butResetsoft = Tkinter.Button(self._frame_5,
            text = "soft reset",
            width = 10,
        )
        self._butStart = Tkinter.Button(self._frame_5,
            text = "start packet",
            width = 10,
        )
        self._butHistory = Tkinter.Button(self._frame_5,
            text = "history",
            width = 10,
        )
        self._butPwd = Tkinter.Button(self._frame_2,
            text = "pwd editor",
            width = 10,
        )
        self._txData = Tkinter.Text(self._frame_7,
            borderwidth = 1,
            height = 0,
            width = 20,
        )
        self._lsLinks = Tkinter.Listbox(self._frame_8,
            activestyle = "dotbox",
            borderwidth = 1,
            height = 0,
            selectmode = "multiple",
            width = 0,
        )
        self._butAdd = Tkinter.Button(self._frame_9,
            text = "add",
            width = 10,
        )
        self._butRemove = Tkinter.Button(self._frame_9,
            text = "remove link",
            width = 10,
        )
        self._butClearall = Tkinter.Button(self._frame_9,
            text = "clear all",
            width = 10,
        )
        self._labStatus = Tkinter.Label(self._frame_10,
            text = "<status information here>",
        )
        self._txLog = Tkinter.Text(self._frame_10,
            borderwidth = 1,
            height = 0,
            width = 25,
        )

        # widget commands

        self._butExit.configure(
            command = self._butExit_command
        )
        self._lsPackets.configure(
            xscrollcommand = self._lsPackets_xscrollcommand
        )
        self._lsPackets.configure(
            yscrollcommand = self._sclPackets.set
        )
        self._sclPackets.configure(
            command = self._sclPackets_command
        )
        self._butKillpacket.configure(
            command = self._butKillpacket_command
        )
        self._butResetsoft.configure(
            command = self._butResetsoft_command
        )
        self._butStart.configure(
            command = self._butStart_command
        )
        self._butHistory.configure(
            command = self._butHistory_command
        )
        self._butPwd.configure(
            command = self._butPwd_command
        )
        self._txData.configure(
            xscrollcommand = self._txData_xscrollcommand
        )
        self._txData.configure(
            yscrollcommand = self._txData_yscrollcommand
        )
        self._lsLinks.configure(
            xscrollcommand = self._lsLinks_xscrollcommand
        )
        self._lsLinks.configure(
            yscrollcommand = self._lsLinks_yscrollcommand
        )
        self._butAdd.configure(
            command = self._butAdd_command
        )
        self._butRemove.configure(
            command = self._butRemove_command
        )
        self._butClearall.configure(
            command = self._butClearall_command
        )
        self._txLog.configure(
            xscrollcommand = self._txLog_xscrollcommand
        )
        self._txLog.configure(
            yscrollcommand = self._txLog_yscrollcommand
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_3.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_4.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_6.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_5.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_1.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_7.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_8.grid(
            in_    = self._frame_7,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_10.grid(
            in_    = self._labelframe_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_9.grid(
            in_    = self._frame_8,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butExit.grid(
            in_    = self._frame_2,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._panedwindow_1.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._lsPackets.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclPackets.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )
        self._butKillpacket.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butResetsoft.grid(
            in_    = self._frame_5,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butStart.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butHistory.grid(
            in_    = self._frame_5,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butPwd.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._txData.grid(
            in_    = self._frame_7,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._lsLinks.grid(
            in_    = self._frame_8,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butAdd.grid(
            in_    = self._frame_9,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butRemove.grid(
            in_    = self._frame_9,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butClearall.grid(
            in_    = self._frame_9,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._labStatus.grid(
            in_    = self._frame_10,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._txLog.grid(
            in_    = self._frame_10,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 1, minsize = 478, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 638, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_10.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_10.grid_columnconfigure(1, weight = 1, minsize = 2, pad = 0)
        self._frame_10.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_rowconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_7.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_8.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_8.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_8.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_9.grid_rowconfigure(1, weight = 0, minsize = 5, pad = 0)
        self._frame_9.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_9.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_9.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._labelframe_1.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)


